stages:
  - package-build
  - package-codegen
  - package-deploy

  - test
  
  - erc-auth-staging
  - deploy-aws-staging
  - deplot-aws-ecs-staging

  - erc-auth-release
  - deploy-aws-release
  - deplot-aws-ecs-release

package-build:
  stage: package-build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  only:
    - package-release
  artifacts:
    paths:
      - ./spec.yml
  script:
    - cd Web.Mock
    - dotnet restore
    - dotnet tool restore
    - dotnet publish -c Release -o /publish_mock
    - cd /publish_mock
    - dotnet swagger tofile --output ./spec.yml --yaml Web.Mock.dll merged_api_versions

package-codegen:
  stage: package-codegen
  image: openapitools/openapi-generator-cli:v6.2.1
  dependencies:
    - package-build
  only:
    - package-release
  artifacts:
    paths:
      - front/
  script:
    - cd /publish_mock
    - generate -g typescript-fetch -i spec.yml -o /front -c /ts-gen-config.json --global-property skipFormModel=false

package-deploy:
  stage: package-deploy
  image: node:latest
  only:
    - package-release
  script:
    - cd /front
    - ls
    - npm install
    - npm config set '//<BASE_GIT_HOST>/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - npm config set '//<BASE_GIT_HOST>/api/v4/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - npm config set @npmClientName:registry https://<BASE_GIT_HOST>/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
    - npm run build
    - npm publish



test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  only:
    - staging
    - release
  script:
    - cd Web.Mock
    - dotnet restore
    - dotnet tool restore
    - dotnet publish -c Release -o /publish_mock
    - cd /publish_mock
    - dotnet swagger tofile --output ./spec.yml --yaml Web.Mock.dll merged_api_versions