stages:
  - npm-api-package-build
  - npm-api-package-codegen
  - npm-api-package-deploy

  - backend-deploy-aws
  - backend-deploy-aws-ecs

include:
  - local: 'Pipelines/backend-deploy.yml'
    inputs:
      environment: backend-staging
      branch: staging
      job_suffix: -staging
      docker_path: Core/Web/Dockerfile

  - local: 'Pipelines/backend-deploy.yml'
    inputs:
      environment: backend-pre-production
      branch: pre-production
      job_suffix: -pre-production
      docker_path: Core/Web/Dockerfile

  - local: 'Pipelines/backend-deploy.yml'
    inputs:
      environment: backend-production
      branch: production
      job_suffix: -production
      docker_path: Core/Web/Dockerfile

  - local: 'Pipelines/npm-api-package-deploy.yml'
    inputs:
      branch: staging
      project_path: ./Core/Web
      project_file: Web.dll
    rules:
      - changes: 
        - Core/Web/Version.targets

  - local: 'Pipelines/npm-api-package-deploy.yml'
    inputs:
      branch: pre-production
      job_suffix: -pre-production
      project_path: ./Core/Web
      project_file: Web.dll
    rules:
      - if: ${CI_COMMIT_REF_SLUG} != 'staging'
      - changes: 
        - Core/Web/Version.targets