version: '3.8'

services:  
  postgres:
    image: postgres:16.1
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    networks:
      - app-network

  backend:
    image: ${DOCKER_REGISTRY-}layeredtemplate-backend
    container_name: layeredtemplate-backend
    env_file:
      - .env
    ports:
      - 3080:3080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Services/App/App.Web/Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge