// <auto-generated />
using System;
using Hipaa.Backend.Plugins.Workflow.Storage.EFCore;
using LayeredTemplate.Plugins.Workflow.Storage.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hipaa.Backend.Plugins.Workflow.Storage.EFCore.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260428202656_WorkflowTenantIndexAndParentStepFk")]
    partial class WorkflowTenantIndexAndParentStepFk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workflow")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hipaa.Backend.Plugins.Workflow.Storage.EFCore.Entities.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Graph")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("graph");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_kind");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TriggerKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trigger_kind");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workflow_definitions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_workflow_definitions_tenant_id");

                    b.HasIndex("TenantId", "OwnerKind", "OwnerId", "TriggerKind")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_definitions_tenant_id_owner_kind_owner_id_trigger_");

                    b.ToTable("workflow_definitions", "workflow");
                });

            modelBuilder.Entity("Hipaa.Backend.Plugins.Workflow.Storage.EFCore.Entities.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AbortReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("abort_reason");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dry_run");

                    b.Property<int>("NestingLevel")
                        .HasColumnType("integer")
                        .HasColumnName("nesting_level");

                    b.Property<Guid?>("ParentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_run_id");

                    b.Property<Guid?>("ParentStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_step_id");

                    b.Property<string>("ReturnValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("return_value");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("StaticContext")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("static_context");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StepsOutputs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("steps_outputs");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TriggerKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trigger_kind");

                    b.Property<Guid?>("TriggerSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("trigger_source_id");

                    b.Property<string>("TriggerSourceKind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trigger_source_kind");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkflowSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("workflow_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_workflow_runs");

                    b.HasIndex("DefinitionId")
                        .HasDatabaseName("ix_workflow_runs_definition_id");

                    b.HasIndex("IsDryRun")
                        .HasDatabaseName("ix_workflow_runs_is_dry_run");

                    b.HasIndex("ParentRunId")
                        .HasDatabaseName("ix_workflow_runs_parent_run_id");

                    b.HasIndex("ParentStepId")
                        .HasDatabaseName("ix_workflow_runs_parent_step_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_workflow_runs_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_workflow_runs_tenant_id");

                    b.HasIndex("Status", "FinishedAt")
                        .HasDatabaseName("ix_workflow_runs_status_finished_at");

                    b.HasIndex("TenantId", "TriggerSourceKind", "TriggerSourceId")
                        .HasDatabaseName("ix_workflow_runs_tenant_id_trigger_source_kind_trigger_source_");

                    b.ToTable("workflow_runs", "workflow");
                });

            modelBuilder.Entity("Hipaa.Backend.Plugins.Workflow.Storage.EFCore.Entities.WorkflowStepExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("node_id");

                    b.Property<string>("OutputPort")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("output_port");

                    b.Property<string>("Outputs")
                        .HasColumnType("jsonb")
                        .HasColumnName("outputs");

                    b.Property<Guid?>("PredecessorExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("predecessor_execution_id");

                    b.Property<string>("ResolvedConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resolved_config");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TriggerPort")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger_port");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workflow_step_executions");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_workflow_step_executions_run_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_workflow_step_executions_tenant_id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_workflow_step_executions_status_next_attempt_at");

                    b.ToTable("workflow_step_executions", "workflow");
                });

            modelBuilder.Entity("Hipaa.Backend.Plugins.Workflow.Storage.EFCore.Entities.WorkflowRun", b =>
                {
                    b.HasOne("Hipaa.Backend.Plugins.Workflow.Storage.EFCore.Entities.WorkflowDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_runs_workflow_definitions_definition_id");

                    b.HasOne("Hipaa.Backend.Plugins.Workflow.Storage.EFCore.Entities.WorkflowRun", null)
                        .WithMany()
                        .HasForeignKey("ParentRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_workflow_runs_workflow_runs_parent_run_id");

                    b.HasOne("Hipaa.Backend.Plugins.Workflow.Storage.EFCore.Entities.WorkflowStepExecution", null)
                        .WithMany()
                        .HasForeignKey("ParentStepId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workflow_runs_workflow_step_executions_parent_step_id");

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("Hipaa.Backend.Plugins.Workflow.Storage.EFCore.Entities.WorkflowStepExecution", b =>
                {
                    b.HasOne("Hipaa.Backend.Plugins.Workflow.Storage.EFCore.Entities.WorkflowRun", "Run")
                        .WithMany("StepExecutions")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_step_executions_workflow_runs_run_id");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Hipaa.Backend.Plugins.Workflow.Storage.EFCore.Entities.WorkflowRun", b =>
                {
                    b.Navigation("StepExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
